### ISSUE TITLE
Only accept @uwaterloo emails

### ISSUE THREAD

**Issue by yucombinator** [icechen1/campuswall#5]

**Comment by Deon** [comment]
Require users signing up using OAuth to verify with a @uwaterloo.ca email first before allowing access:

Signup -> Enter Email -> Continue signup locally or using a social network.

**Comment by Deon** [comment]
Working on this in the [emailAuth Branch](https://github.com/icechen1/campuswall/tree/emailAuth).

**Comment by youwayx** [comment]
is this issue fixed now?

**Comment by Deon** [comment]
Facebook Auth: 11c2b8e7b952786f2df834c64283e4c7a8b60252
Twitter Auth: 49087db5dbc7f9ebc14591c67924a2b3d7ee79b1
Github and Google: 110d493b1b77bf2f8875999cab5d5f8985d93796

Removed LinkedIn OAuth due to hassle.

Users cannot create events without first "verifying" with an UW email address.
